### ISSUE TITLE
node4.3 is deprecated runtime

### ISSUE THREAD

**Issue by pioneerit** [scalyr/cloudwatch2scalyr#8]
https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
The last possible usage of that code was on April 30, 2019.

Do you have plans to update it for `Node.js 10.x`?

**Comment by MarkoTechno** [comment]
We have implemented a new solution for importing CloudWatch data into Scalyr, which is documented here: https://www.scalyr.com/solutions/import-cloudwatch
